# Generated by Django 2.2 on 2024-02-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sourceshare',
            name='source_share_end_date',
        ),
        migrations.RemoveIndex(
            model_name='sourceshare',
            name='source_share_start_date',
        ),
        migrations.RemoveField(
            model_name='sourceshare',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sourceshare',
            name='start_date',
        ),
    ]
