# Generated by Django 2.2 on 2024-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_remove_dates_from_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='accumulating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='retention',
            field=models.IntegerField(default=3650),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['accumulating'], name='source_accumulating'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['retention'], name='source_retention'),
        ),
    ]
