# Generated by Django 2.2 on 2024-04-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_source_retention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='amber_high',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='amber_low',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='red_high',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='red_low',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
