# Generated by Django 5.0.10 on 2025-01-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0004_alerts_null_if_accumulating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='source',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourceshare',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sourceshare',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
